from __future__ import annotations

import argparse
import json
from dataclasses import asdict, dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any

from jarvis.runtime.news_coverage_readiness import build_news_coverage_readiness_result


STATUS_READY = "JARVIS_V112_0_ASSISTANT_NEWS_CONTEXT_READY_SAFE"
STATUS_REVIEW_REQUIRED = "JARVIS_V112_0_ASSISTANT_NEWS_CONTEXT_REVIEW_REQUIRED_SAFE"
DEFAULT_OUTPUT_PATH = "outputs/assistant_news_context_latest.json"


@dataclass(frozen=True)
class AssistantNewsContextResult:
    status: str
    current_date: str
    categories: list[str]
    covered_categories: list[str]
    missing_categories: list[str]
    local_cached_news_available: bool
    live_fetch_enabled: bool
    manual_review_required: bool
    summary: str
    source: str
    as_of: str
    freshness: str
    confidence: str
    warnings: list[str]
    blockers: list[str]
    execution_forbidden: bool
    broker_connection: bool
    credentials_used: bool
    order_created: bool
    trade_executed: bool
    report_written: bool
    report_path: str

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


@lru_cache(maxsize=8)
def _build_readonly_news_context(current_date: str) -> AssistantNewsContextResult:
    readiness = build_news_coverage_readiness_result(current_date=current_date)
    blockers = list(readiness.blockers)
    warnings = [
        "Live news fetch is not enabled. I can only report readiness/local cached news.",
        "No headlines, causes, or market-moving claims are generated by this tool.",
        "Manual review is required before relying on any external news.",
    ]
    summary = (
        "News coverage categories are configured for manual review, but live news fetching is disabled. "
        "No local headline cache is reported by this assistant context."
    )
    return AssistantNewsContextResult(
        status=STATUS_READY if not blockers else STATUS_REVIEW_REQUIRED,
        current_date=current_date,
        categories=list(readiness.required_categories),
        covered_categories=list(readiness.covered_categories),
        missing_categories=list(readiness.missing_categories),
        local_cached_news_available=False,
        live_fetch_enabled=False,
        manual_review_required=True,
        summary=summary,
        source="news_coverage_readiness",
        as_of=current_date,
        freshness="readiness_only_no_live_news",
        confidence="medium_for_readiness_low_for_headlines",
        warnings=warnings + list(readiness.warnings),
        blockers=blockers,
        execution_forbidden=True,
        broker_connection=False,
        credentials_used=False,
        order_created=False,
        trade_executed=False,
        report_written=False,
        report_path=str(DEFAULT_OUTPUT_PATH),
    )


def build_assistant_news_context_result(
    *,
    current_date: str = "2026-06-18",
    output_path: str | Path = DEFAULT_OUTPUT_PATH,
    write_report: bool = False,
) -> AssistantNewsContextResult:
    result = _build_readonly_news_context(current_date)
    if write_report:
        result = AssistantNewsContextResult(
            **{
                **result.to_dict(),
                "report_written": True,
                "report_path": str(output_path),
            }
        )
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        Path(output_path).write_text(
            json.dumps(result.to_dict(), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
    return result


def format_assistant_news_context(result: AssistantNewsContextResult) -> str:
    return "\n".join(
        [
            "Live news fetch is not enabled. I can only report readiness/local cached news.",
            f"Coverage categories: {', '.join(result.categories)}.",
            f"Missing categories: {', '.join(result.missing_categories) or 'none'}.",
            f"Manual review required: {result.manual_review_required}.",
            f"Summary: {result.summary}",
            (
                "Data / Source / Freshness: "
                f"source={result.source}; as_of={result.as_of}; freshness={result.freshness}; "
                f"confidence={result.confidence}; live fetch enabled={result.live_fetch_enabled}; "
                f"local cached news available={result.local_cached_news_available}."
            ),
            "Manual checklist: check reputable external headlines, source timestamps, and relevance before any external action.",
            "Safety: read-only news context. No broker, order, trade, buy/sell request, headline fabrication, or auto-approval path is enabled.",
        ]
    )


def format_assistant_news_context_report(result: AssistantNewsContextResult) -> str:
    lines = [
        "J.A.R.V.I.S. ASSISTANT NEWS CONTEXT",
        f"status: {result.status}",
        f"current date: {result.current_date}",
        f"live fetch enabled: {result.live_fetch_enabled}",
        f"local cached news available: {result.local_cached_news_available}",
        f"manual review required: {result.manual_review_required}",
        f"source: {result.source}",
        f"as_of: {result.as_of}",
        f"freshness: {result.freshness}",
        f"confidence: {result.confidence}",
        "",
        "CATEGORIES:",
        f"- required: {', '.join(result.categories)}",
        f"- covered: {', '.join(result.covered_categories) or 'none'}",
        f"- missing: {', '.join(result.missing_categories) or 'none'}",
        "",
        "WARNINGS:",
    ]
    lines.extend(f"- {warning}" for warning in result.warnings or ["none"])
    lines.append("")
    lines.append("BLOCKERS:")
    lines.extend(f"- {blocker}" for blocker in result.blockers or ["none"])
    lines.extend(
        [
            "",
            "SAFETY:",
            f"- execution forbidden: {result.execution_forbidden}",
            f"- broker connection: {result.broker_connection}",
            f"- credentials used: {result.credentials_used}",
            f"- order created: {result.order_created}",
            f"- trade executed: {result.trade_executed}",
            "",
            "HUMAN REPLY:",
            format_assistant_news_context(result),
        ]
    )
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Run J.A.R.V.I.S. assistant news context.")
    parser.add_argument("--assistant-news-context", action="store_true")
    parser.add_argument("--current-date", default="2026-06-18")
    parser.add_argument("--write-report", action="store_true")
    parser.add_argument("--output-path", default=DEFAULT_OUTPUT_PATH)
    args = parser.parse_args(argv)

    result = build_assistant_news_context_result(
        current_date=args.current_date,
        output_path=args.output_path,
        write_report=args.write_report,
    )
    print(format_assistant_news_context_report(result))
    return 0 if not result.blockers else 1


__all__ = [
    "STATUS_READY",
    "STATUS_REVIEW_REQUIRED",
    "AssistantNewsContextResult",
    "build_assistant_news_context_result",
    "format_assistant_news_context",
    "format_assistant_news_context_report",
    "main",
]
